In [2]:
%pip install json

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json
WARNING: You are using pip version 22.0.4; however, version 23.1 is available.
You should consider upgrading via the 'C:\Users\fauch\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

In [3]:
import pandas as pd

df = pd.read_csv("./raw_CO2.csv", sep=";")
df.head()

,Code AGB,Code CIQUAL,Groupe d'aliment,Sous-groupe d'aliment,Nom du Produit en Français,LCI Name,DQR,Nom et code,Agriculture,Transformation,Emballage,Transport,Supermarché et distribution,Consommation,Total
0,11084,11084,aides culinaires et ingrédients divers,algues,"Agar (algue), cru","Seaweed, agar, raw","2,99","Agar (algue), cru (11084)","4,57","1,49","0,29","0,38","0,02","0,01","6,77"
1,11023,11023,aides culinaires et ingrédients divers,herbes,"Ail séché, poudre","Garlic, powder, dried","4,11","Ail séché, poudre (11023)","0,07","0,00","0,48","0,19","0,02","0,00","0,75"
2,11000,11000,aides culinaires et ingrédients divers,herbes,"Ail, cru","Garlic, fresh","3,54","Ail, cru (11000)","0,08","0,00","0,00","0,17","0,02","0,08","0,36"
3,11093,11093,aides culinaires et ingrédients divers,herbes,"Aneth, frais","Dill, fresh","3,75","Aneth, frais (11093)","0,22","0,00","0,33","0,16","0,02","0,08","0,82"
4,20995,20995,aides culinaires et ingrédients divers,algues,"Ao-nori (Enteromorpha sp.), séchée ou déshydratée","Sea lettuce (Enteromorpha sp.), dried or dehyd...","2,99","Ao-nori (Enteromorpha sp.), séchée ou déshydra...","4,57","1,49","0,29","0,38","0,02","0,01","6,77"

In [4]:
# we just need to translate the food group
x = pd.unique(df["Groupe d'aliment"])
print(len(x))
translated_x = [
    "culinary aids and miscellaneous ingredients", "baby food", "beverages", "starters and mixed dishes", "fruits, vegetables, legumes and oilseeds", 
    "ice creams and sherbets", "milk and dairy products", "fats", "cereal products", "sweetened products", "meat, eggs, fish"
]
print(len(translated_x))
translation_dict = {}
for group_index in range(len(x)): translation_dict[x[group_index]] = translated_x[group_index]

df['Food Group'] = [translation_dict[fr_group] for fr_group in df["Groupe d'aliment"]]
df.head()

11
11

,Code AGB,Code CIQUAL,Groupe d'aliment,Sous-groupe d'aliment,Nom du Produit en Français,LCI Name,DQR,Nom et code,Agriculture,Transformation,Emballage,Transport,Supermarché et distribution,Consommation,Total,Food Group
0,11084,11084,aides culinaires et ingrédients divers,algues,"Agar (algue), cru","Seaweed, agar, raw","2,99","Agar (algue), cru (11084)","4,57","1,49","0,29","0,38","0,02","0,01","6,77",culinary aids and miscellaneous ingredients
1,11023,11023,aides culinaires et ingrédients divers,herbes,"Ail séché, poudre","Garlic, powder, dried","4,11","Ail séché, poudre (11023)","0,07","0,00","0,48","0,19","0,02","0,00","0,75",culinary aids and miscellaneous ingredients
2,11000,11000,aides culinaires et ingrédients divers,herbes,"Ail, cru","Garlic, fresh","3,54","Ail, cru (11000)","0,08","0,00","0,00","0,17","0,02","0,08","0,36",culinary aids and miscellaneous ingredients
3,11093,11093,aides culinaires et ingrédients divers,herbes,"Aneth, frais","Dill, fresh","3,75","Aneth, frais (11093)","0,22","0,00","0,33","0,16","0,02","0,08","0,82",culinary aids and miscellaneous ingredients
4,20995,20995,aides culinaires et ingrédients divers,algues,"Ao-nori (Enteromorpha sp.), séchée ou déshydratée","Sea lettuce (Enteromorpha sp.), dried or dehyd...","2,99","Ao-nori (Enteromorpha sp.), séchée ou déshydra...","4,57","1,49","0,29","0,38","0,02","0,01","6,77",culinary aids and miscellaneous ingredients

In [5]:
# we just need to translate the food subgroup
food_subgroup = pd.unique(df["Sous-groupe d'aliment"])
translated_food_subgroup = ['seaweed', 'herbs', 'various ingredients', 'spices', 'cooking aids', 'sauces', 'salts', 'condiments', 'foodstuffs intended for particular nutritional uses', 'infant cereals & cookies', 'infant milks & drinks', 'infant desserts', 'salted snacks & infant dishes', 'alcoholic beverages', 'non-alcoholic beverages', 'water', 'mixed dishes', 'puff pastry & other starters', 'soups', 'vegetarian dishes', 'sandwiches', 'pizzas, pies & savoury pancakes', 'mixed salads & raw vegetables', 'fruits', 'nuts & oil seeds', 'vegetables', 'potatoes & other tubers', 'pulses', 'ice creams', 'frozen desserts', 'sherbets', 'cheeses', 'fresh dairy products & similar', 'creams & cream specialities', 'milks', 'butters', 'vegetable oils & fats', 'other fats', 'fish oils', 'margarines', 'pasta, rice & cereals', 'flours & pastries', 'cakes & pastries', 'breads & pastries', 'breakfast cereals & cookies', 'chocolates & chocolate products', 'non-chocolate confectionery', 'jams & similar', 'sugars, honeys & similar', 'fish & seafood products', 'cooked meat', 'raw meat', 'raw fish', 'cold cuts', 'cooked fish', 'other meat products', 'meat substitutes', 'cooked shellfish', 'raw shellfish', 'eggs', 'cold cut substitutes']

translation_dict = {}
for subgroup_index in range(len(food_subgroup)): translation_dict[food_subgroup[subgroup_index]] = translated_food_subgroup[subgroup_index]

df['Food subgroup'] = [ translation_dict[fr_subgroup] for fr_subgroup in df["Sous-groupe d'aliment"]]
df.tail()

,Code AGB,Code CIQUAL,Groupe d'aliment,Sous-groupe d'aliment,Nom du Produit en Français,LCI Name,DQR,Nom et code,Agriculture,Transformation,Emballage,Transport,Supermarché et distribution,Consommation,Total,Food Group,Food subgroup
2512,6535,6535,"viandes, œufs, poissons",viandes crues,"Veau, steak haché 20% MG, cru","Veal, minced steak, 20% fat, raw","2,47","Veau, steak haché 20% MG, cru (6535)","21,70","0,24","0,28","0,21","0,04","0,01","22,40","meat, eggs, fish",raw meat
2513,6582,6582,"viandes, œufs, poissons",viandes cuites,"Veau, tête, bouillie/cuite à l'eau","Calf, head, boiled/cooked in water","2,45","Veau, tête, bouillie/cuite à l'eau (6582)","22,30","0,07","0,44","0,32","0,06","0,34","23,60","meat, eggs, fish",cooked meat
2514,26146,26146,"viandes, œufs, poissons",poissons crus,"Vivaneau, cru","Snapper, raw","3,68","Vivaneau, cru (26146)","3,14","0,00","0,28","0,79","0,04","0,01","4,25","meat, eggs, fish",raw fish
2515,26147,26147,"viandes, œufs, poissons",poissons cuits,"Vivaneau, cuit","Snapper, cooked","3,56","Vivaneau, cuit (26147)","3,84","0,00","0,23","0,96","0,05","0,09","5,16","meat, eggs, fish",cooked fish
2516,25512,25512,"viandes, œufs, poissons",autres produits à base de viande,"Volaille, croquette panée ou nuggets",Poultry nuggets,"2,79","Volaille, croquette panée ou nuggets (25512)","4,63","0,59","0,48","0,21","0,04","0,09","6,04","meat, eggs, fish",other meat products

In [6]:
import json

CO2_dict = {}

for index, row in df.iterrows():
    CO2_dict[row['LCI Name']] = {
        'agriculture': float(row['Agriculture'].replace(',', '.')),
        'transformation': float(row['Transformation'].replace(',', '.')),
        'packaging': float(row['Emballage'].replace(',', '.')),
        'transportation': float(row['Transport'].replace(',', '.')),
        'distribution': float(row['Supermarché et distribution'].replace(',', '.')),
        'consumption': float(row['Consommation'].replace(',', '.')),
        'total': float(row['Total'].replace(',', '.'))
    }

with open("raw_CO2.json", "w") as write_file:
    json.dump(CO2_dict, write_file,  indent=4)

In [7]:
translated_df = df[['LCI Name', 'Agriculture', 'Transformation', 'Emballage', 'Transport', 'Supermarché et distribution', 'Consommation', 'Total', 'Food Group', 'Food subgroup']].copy()
cols = ['Agriculture', 'Transformation', 'Emballage', 'Transport', 'Supermarché et distribution', 'Consommation', 'Total']

for col in cols: translated_df[col] = [float(x.replace(',', '.')) for x in translated_df[col]]

translated_df.head()

,LCI Name,Agriculture,Transformation,Emballage,Transport,Supermarché et distribution,Consommation,Total,Food Group,Food subgroup
0,"Seaweed, agar, raw",4.57,1.49,0.29,0.38,0.02,0.01,6.77,culinary aids and miscellaneous ingredients,seaweed
1,"Garlic, powder, dried",0.07,0.00,0.48,0.19,0.02,0.00,0.75,culinary aids and miscellaneous ingredients,herbs
2,"Garlic, fresh",0.08,0.00,0.00,0.17,0.02,0.08,0.36,culinary aids and miscellaneous ingredients,herbs
3,"Dill, fresh",0.22,0.00,0.33,0.16,0.02,0.08,0.82,culinary aids and miscellaneous ingredients,herbs
4,"Sea lettuce (Enteromorpha sp.), dried or dehyd...",4.57,1.49,0.29,0.38,0.02,0.01,6.77,culinary aids and miscellaneous ingredients,seaweed

In [8]:
food_groups = pd.unique(translated_df['Food Group'])
food_subgroups = pd.unique(translated_df['Food subgroup'])

mean_f_groups = {}
for group in food_groups:
    tmp_df = translated_df[translated_df['Food Group'] == group]
    mean_f_groups[group] = tmp_df['Total'].mean()

mean_f_subgroups = {}
for subgroup in food_subgroups:
    tmp_df = translated_df[translated_df['Food subgroup'] == subgroup]
    mean_f_subgroups[subgroup] = tmp_df['Total'].mean()

translated_df['Group mean'] = [mean_f_groups[group] for group in translated_df['Food Group']]
translated_df['Subgroup mean'] = [mean_f_subgroups[subgroup] for subgroup in translated_df['Food subgroup']]

translated_df.head()

,LCI Name,Agriculture,Transformation,Emballage,Transport,Supermarché et distribution,Consommation,Total,Food Group,Food subgroup,Group mean,Subgroup mean
0,"Seaweed, agar, raw",4.57,1.49,0.29,0.38,0.02,0.01,6.77,culinary aids and miscellaneous ingredients,seaweed,3.142625,6.675000
1,"Garlic, powder, dried",0.07,0.00,0.48,0.19,0.02,0.00,0.75,culinary aids and miscellaneous ingredients,herbs,3.142625,1.170417
2,"Garlic, fresh",0.08,0.00,0.00,0.17,0.02,0.08,0.36,culinary aids and miscellaneous ingredients,herbs,3.142625,1.170417
3,"Dill, fresh",0.22,0.00,0.33,0.16,0.02,0.08,0.82,culinary aids and miscellaneous ingredients,herbs,3.142625,1.170417
4,"Sea lettuce (Enteromorpha sp.), dried or dehyd...",4.57,1.49,0.29,0.38,0.02,0.01,6.77,culinary aids and miscellaneous ingredients,seaweed,3.142625,6.675000

In [22]:
CO2_emissions = sorted(translated_df['Total'])
num_products = len(sorted(CO2_emissions))
print('There is ' + str(num_products) + ' products')
# There is 2517 products
print(num_products/3)
# first third
print('//////////////////////////////////////')
print(CO2_emissions[838])
print(CO2_emissions[1676])

There is 2517 products
839.0
//////////////////////////////////////
1.51
5.09